### PR TITLE
Animations

### PR DESCRIPTION
**Pull request by yayoamigo**
Update the readme file

### CODE REVIEW

**Review by christianbiring1 — CHANGES_REQUESTED** [review]
Hi @yayoamigo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :tada: 
164625215-44f24c98-53c8-49c1-b68f-05723a584dc2
## Highlights
- [ ] All linters are green

## Required Changes ♻️

 - [ ] Kindly make sure your app is deployed successfully and you provide the link to your portfolio in your README file as stated in the project requirement
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yayoamigo** [comment]
hi @christianbiring1   can you be more specific about whats wrong with my deployement ? as you can see from this link the deployement seems to be succesfull https://yayoamigo.github.io/mobile-template/

**Comment by christianbiring1** [comment]
> hi @christianbiring1 can you be more specific about whats wrong with my deployement ? as you can see from this link the deployement seems to be succesfull https://yayoamigo.github.io/mobile-template/

### if you can check very well your commit history and the time. I think you would agree with me that you deployed the page after I have reviewed your PR, right?

**Comment by yayoamigo** [comment]
@christianbiring1 actually no, I just added the link to the README file, the page was already deployed before your review. So please be thorough :)

**Pull request merged**
